// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCzXVHTcWQ3IqP7Yrxo49-h-ji8eNOMOU',
    appId: '1:1081648048066:web:b70519cdf4b7c634bad85b',
    messagingSenderId: '1081648048066',
    projectId: 'flutter-app-13c17',
    authDomain: 'flutter-app-13c17.firebaseapp.com',
    storageBucket: 'flutter-app-13c17.appspot.com',
    measurementId: 'G-PF3XZHY78H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEADQ1DvyaoRuTCBMAb_8kKePg__2lcoE',
    appId: '1:1081648048066:android:b3ea7634f4861344bad85b',
    messagingSenderId: '1081648048066',
    projectId: 'flutter-app-13c17',
    storageBucket: 'flutter-app-13c17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoTDVn7NeqG-qOd_2rxmDRRMUwMSzoC8s',
    appId: '1:1081648048066:ios:aad149853171f4c7bad85b',
    messagingSenderId: '1081648048066',
    projectId: 'flutter-app-13c17',
    storageBucket: 'flutter-app-13c17.appspot.com',
    iosClientId: '1081648048066-jb6uelgp57c4cqn2tiqi38bdtcolmj9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontendMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoTDVn7NeqG-qOd_2rxmDRRMUwMSzoC8s',
    appId: '1:1081648048066:ios:aad149853171f4c7bad85b',
    messagingSenderId: '1081648048066',
    projectId: 'flutter-app-13c17',
    storageBucket: 'flutter-app-13c17.appspot.com',
    iosClientId: '1081648048066-jb6uelgp57c4cqn2tiqi38bdtcolmj9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontendMobile',
  );
}
